In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data01 = pd.read_excel('data/0-1.xls')
data02 = pd.read_excel('data/0-2.xls')
data11 = pd.read_excel('data/1-1.xls')
data12 = pd.read_excel('data/1-2.xls')
data11.head()

,序号,提交答卷时间,所用时间,来源,来源详情,来自IP,rumors,M1-1,M1-2,M1-3,...,M3-1,M3-2,M3-3,M3-4,M3-5,M4-1,M4-2,M4-3,M4-4,总分
0,1,2019/12/3 10:19:40,144秒,样本服务,NaN,58.63.2.128(广东-广州),2,3,3,3,...,3,2,2,3,2,3,3,3,2,58
1,2,2019/12/3 10:22:40,140秒,样本服务,NaN,27.36.141.140(广东-佛山),1,1,1,2,...,1,3,1,1,2,1,1,2,1,32
2,3,2019/12/3 10:26:25,118秒,样本服务,NaN,111.32.52.135(天津-天津),3,3,2,2,...,3,2,2,2,2,3,3,3,2,54
3,4,2019/12/3 10:26:26,123秒,样本服务,NaN,112.17.239.46(浙江-杭州),5,3,3,2,...,2,1,3,1,1,1,3,3,3,55
4,5,2019/12/3 10:27:25,117秒,样本服务,NaN,112.17.247.194(浙江-杭州),3,2,2,2,...,1,1,1,1,1,2,1,1,2,35

In [6]:
l = [data01, data02, data11, data12]
l[0].head()

,序号,提交答卷时间,所用时间,来源,来源详情,来自IP,rumors,M1-1,M1-2,M1-3,...,M3-1,M3-2,M3-3,M3-4,M3-5,M4-1,M4-2,M4-3,M4-4,总分
0,1,2019/12/3 10:19:15,122秒,样本服务,NaN,223.104.65.164(广东-未知),5,3,4,2,...,3,2,2,2,2,2,2,2,2,58
1,2,2019/12/3 10:21:11,116秒,样本服务,NaN,223.104.20.221(湖北-武汉),1,3,4,3,...,1,2,2,1,2,4,3,2,3,57
2,3,2019/12/3 10:22:16,166秒,样本服务,NaN,112.224.65.99(山东-青岛),2,2,3,2,...,3,2,2,1,1,1,2,2,2,50
3,4,2019/12/3 10:22:38,133秒,样本服务,NaN,120.230.44.34(广东-佛山),4,3,3,4,...,4,3,3,3,3,4,3,3,3,69
4,5,2019/12/3 10:23:15,117秒,样本服务,NaN,27.18.133.242(湖北-武汉),3,1,3,3,...,4,3,3,2,3,2,3,4,3,64

In [10]:
for i in range(len(l)):
    l[i]['SUM1'] = l[i].loc[:,'M1-1':'M1-6'].sum(axis=1)
    l[i]['SUM2'] = l[i].loc[:,'M2-1':'M2-6'].sum(axis=1)
    l[i]['SUM3'] = l[i].loc[:,'M3-1':'M3-5'].sum(axis=1)
    l[i]['SUM4'] = l[i].loc[:,'M4-1':'M4-4'].sum(axis=1)
data01.head()

,序号,提交答卷时间,所用时间,来源,来源详情,来自IP,rumors,M1-1,M1-2,M1-3,...,M3-5,M4-1,M4-2,M4-3,M4-4,总分,SUM1,SUM2,SUM3,SUM4
0,1,2019/12/3 10:19:15,122秒,样本服务,NaN,223.104.65.164(广东-未知),5,3,4,2,...,2,2,2,2,2,58,18,21,11,8
1,2,2019/12/3 10:21:11,116秒,样本服务,NaN,223.104.20.221(湖北-武汉),1,3,4,3,...,2,4,3,2,3,57,19,18,8,12
2,3,2019/12/3 10:22:16,166秒,样本服务,NaN,112.224.65.99(山东-青岛),2,2,3,2,...,1,1,2,2,2,50,14,20,9,7
3,4,2019/12/3 10:22:38,133秒,样本服务,NaN,120.230.44.34(广东-佛山),4,3,3,4,...,3,4,3,3,3,69,20,20,16,13
4,5,2019/12/3 10:23:15,117秒,样本服务,NaN,27.18.133.242(湖北-武汉),3,1,3,3,...,3,2,3,4,3,64,15,22,15,12

In [13]:
data01[['SUM1','SUM2','SUM3','SUM4']].to_csv('data/data01.csv', index=False)
data02[['SUM1','SUM2','SUM3','SUM4']].to_csv('data/data02.csv', index=False)
data11[['SUM1','SUM2','SUM3','SUM4']].to_csv('data/data11.csv', index=False)
data12[['SUM1','SUM2','SUM3','SUM4']].to_csv('data/data12.csv', index=False)

In [19]:
import pandas as pd

# data01 = pd.read_csv('data/data01.csv')
# data02 = pd.read_csv('data/data02.csv')
# data11 = pd.read_csv('data/data11.csv')
# data12 = pd.read_csv('data/data12.csv')
data01 = pd.read_excel('data/0-1.xls')
data02 = pd.read_excel('data/0-2.xls')
data11 = pd.read_excel('data/1-1.xls')
data12 = pd.read_excel('data/1-2.xls')

In [20]:
desc01 = data01.describe()
desc01.to_csv('results/desc01.csv')

In [21]:
desc02 = data02.describe()
desc02.to_csv('results/desc02.csv')

In [22]:
desc11 = data11.describe()
desc11.to_csv('results/desc11.csv')

In [23]:
desc12 = data12.describe()
desc12.to_csv('results/desc12.csv')